### PR TITLE
Use function_exported/3 to test for callbacks

### PR DESCRIPTION
**Pull request by rnewson**
try/catch is much slower in comparison to function_exported.

### CODE REVIEW

**Comment by rnewson** [comment]
this fixes a performance regression from the introduction of couch_epi.

**Comment by kxepal** [comment]
Good catch. Never liked try/catch. May be fix other modules as well? So far:
- couch_epi_data:get_from_module/1
- couch_epi_data:current/2
- couch_epi_data_source:current/2
- couch_epi_functions_gen:get_current_definitions/1
- couch_epi_functions_gen:get_current_is_updated/3
- couch_epi_functions_gen:dispatch/5
- couch_epi_functions_gen:provides/4

I think generic catch Class:Reason should be also revised, but didn't dig into to say for sure.

**Comment by eiri** [comment]
This two probably need the same treatment:

https://github.com/apache/couchdb-couch-epi/blob/master/src/couch_epi_data.erl#L137-L142
https://github.com/apache/couchdb-couch-epi/blob/master/src/couch_epi_functions_gen.erl#L253-L259

**Comment by rnewson** [comment]
ah good catch, missed those

**Comment by rnewson** [comment]
ilya to follow up with better fix

**Pull request closed without merging**
