### PR TITLE
Fix crypto deprecations

### PR DESCRIPTION
**Pull request by kxepal**
COUCHDB-2825

### CODE REVIEW

**Comment by rnewson** [comment]
this isn't a 'fix' :)

**Comment by kxepal** [comment]
What it have to be then? I'm confused.

**Comment by rnewson** [comment]
You've just suppressed the warning, when the function is removed, couch_epi will break, which is not the case elsewhere.

**Comment by rnewson** [comment]
ooh, never mind. Ilya took care of this already. fine...

+1

**Pull request merged**
